### ISSUE TITLE
More info in dialogs when identity fails

### ISSUE THREAD

**Issue by concordium-cl** [Concordium/concordium-desktop-wallet#102]
**Description**
1. When selecting a failed account on the account page, a dlg pops up. Please add the following sentence: **The account will be automatically removed when you delete the related failed identity.** 

![failure dlg](https://user-images.githubusercontent.com/69570978/135238911-e0ab8d3d-a78c-41e2-8061-0c8739366fef.JPG)

2. When an identity issuance fails, a dlg pops up. Please change the last sentence to: **The identity can be removed by deleting the identity card in the identity view. This will automatically delete the related initial account as well.** And while your add it, please add a period after the first sentence ;-) 

![failure_dlg_2](https://user-images.githubusercontent.com/69570978/135239611-32441e1f-2c15-4f85-9f0d-f4b3df000ce9.JPG)

**Steps to Reproduce**
Let an identity issuance fail.

**Versions**
- DW 1.2.0 beta2
- Windows
- Chrome

**Comment by concordium-cl** [comment]
@jens-concordium: Can you review the new sentences and make changes if needed? Thx.

**Comment by jens-concordium** [comment]
@concordium-cl I updated the first sentence as well.
