### ISSUE TITLE
Notabene's terms and/or privacy statements cannot be closed without restarting the Ledger flow

### ISSUE THREAD

**Issue by concordium-cl** [Concordium/concordium-desktop-wallet#103]
**Description**
When initiating the Notabene flow, the user first has to confirm some actions on the Ledger (e.g. confirm pk, confirm identity provider keys). Then a Notabene info text is shown with links to Notabene's terms and privacy statements. When following those links, the only possibility to close the statements and proceed with the flow is to either use X or the back button. Both options relate to the identity flow itself and thereby restart it. There is no option to close the Notabene subpage. Hence, the user must redo all the Ledger confirmations.

![nb](https://user-images.githubusercontent.com/69570978/135243441-d68c3897-977d-4895-8f51-6ebd19a32b1a.JPG)

**Steps to Reproduce**
- initiate id flow with notabene
- confirm all initial actions on Ledger
- on page "verify your identity with Notabene", open either "Terms" or "Privacy"
- clich X or < 

**Expected Result**
Closing X that relates to the Notabene subpage, so that only subpages close and user can click "Get started" and progress in the flow.

**Actual Result**
Only existing buttons relate to the identity flow. Identity flow is restarted.

**Versions**
- dw 1.2.0 beta2
- Windows
- Chrome

**Comment by shjortConcordium** [comment]
Reasons for rejecting:
- Placing the extra back button is quite hard/weird.
- Can be circumvented either by going back to signing, or using back button on mouse.
- Weird to have a back button in Onfido flow, where there already is one. This might also be the case for future identity providers.
