### ISSUE TITLE
Use arrow keys to browse back and forth in time component

### ISSUE THREAD

**Issue by jens-concordium** [Concordium/concordium-desktop-wallet#115]
**Description**
When entering date and time in the date and time component, it is currently not possible to change back and forth between fields with the arrows on the keyboards. It would be nice if that was possible.

![Image 30-09-2021 at 15 24](https://user-images.githubusercontent.com/76045015/135463666-aa4915da-1f99-4b49-8527-bb610f55b40a.jpg)

**Expected Result**
That it would be possible to use right and left arrow keys on the keyboard to change back and forth between fields.

**Actual Result**
It's not possible to change back and forth.

**Versions**
- Software Version: 1.2.0-beta.2
- OS: MacOS 11.5.2

**Comment by orhoj** [comment]
@jens-concordium Wouldn't it be better to replace it with an actual datetime picker instead of improving on this component?

**Comment by jens-concordium** [comment]
@orhoj, yeah that's a good idea. Do you know of any that are not terrible, or too far from our aesthetic?

**Comment by soerenbf** [comment]
@jens-concordium @orhoj I can have a look next week. Then @jens-concordium and I can discuss which option will fit best.

**Comment by jens-concordium** [comment]
Sounds good!

**Comment by soerenbf** [comment]
We're going with [react-datepicker](https://www.npmjs.com/package/react-datepicker) as a datepicker component, as it is simple, features date/time and is customizable and accessible. I'll make a new issue and close this one.

**Comment by soerenbf** [comment]
Closing this in favour of #124
