### ISSUE TITLE
Date and time errors when making account reports

### ISSUE THREAD

**Issue by jens-concordium** [Concordium/concordium-desktop-wallet#116]
**Bug Description**
When making an account report and setting the "To:" time too close to the current time, yields and error.

The wallet says "Date must be before today", even though it should be possible to make the report from today.

If the time is set to an hour before the current time, the wallet doesn't give you any errors.

![Image 30-09-2021 at 15 36](https://user-images.githubusercontent.com/76045015/135465897-8b558c6c-aed2-42e7-ab6b-09424edf4f9d.jpg)
**Steps to Reproduce**

**Expected Result**
It should be possible to make a report all the way up to the current time. If the user enters a time in the future, the error message should not be "Date must be before today", but something like "The time cannot be in the future" or something.

**Actual Result**
It is not possible to make a report that goes all the way up past the last hour, and it says "Date must be before today"

**Versions**
- Software Version: 1.2.0-beta.2
- OS: MacOS 11.5.2

**Comment by shjortConcordium** [comment]
@soerenbf, I think you should take this, because not being able to choose a time within the current hour doesn't happen on Linux (might be a Mac only issue)
