### ISSUE TITLE
Reverse transaction ordering fetched from wallet proxy

### ISSUE THREAD

**Issue by soerenbf** [Concordium/concordium-desktop-wallet#13]
**Description**
Currently we fetch the oldest transactions first, but the newest transactions are quite likely the ones of the highest interest to a user. It is not feasible that a user has to wait for all transactions to be loaded before they can see their transactions from today.

Furthermore, it makes more sense to only fetch the transactions needed to display the most recent N transactions for an account instead of fetching all the transactions to filter them client side (to not overload the wallet proxy).

For generating an account report, we will probably need to recursively fetch transactions until the list of transactions for the respective account(s) have been exhausted.

**Dependent on**
- https://github.com/Concordium/concordium-wallet-proxy/pull/16

**Sub-tasks**
- [ ] Fetch transactions for account view based on filters and in descending order.
- [ ] Fetch transactions for account(s) report instead of basing it on data from DB.

**Comment by concordium-cl** [comment]
@soerenbf: What's the status of that?

**Comment by soerenbf** [comment]
> @soerenbf: What's the status of that?

Yes, I looked it over this morning as well, and couldn't quite figure it out. I'll process this one of the days i get into the office, and close it if necessary.

**Comment by soerenbf** [comment]
@concordium-cl We talked it over, and it's still something that would bring value in the long run (for people with a lot of transactions on their account, e.g. bakers, finalizers, etc.), but it's an optimization more than a necessity, and it's tricky to solve.

I'll unassign myself for now, but it should still remain in the issues list.

**Comment by orhoj** [comment]
This will quite likely be solved and made obsolete by: https://github.com/Concordium/concordium-desktop-wallet/issues/153.

**Comment by orhoj** [comment]
This issue is no longer relevant due to the solution to #153, which makes sure that newest transactions are fetched first. We no longer synchronize all transactions from the wallet proxy, but only the ones to be shown to the user.
