### ISSUE TITLE
Disable the "CCD drop button" after it's been clicked. 

### ISSUE THREAD

**Issue by EmilLa1** [Concordium/concordium-desktop-wallet#190]
**Description**
Very minor but here goes.
Currently when clicked the "CCD drop button" is not being disabled. 

Maybe it should be disabled after the user has clicked it in order to provide "immediate feedback" for the user. 

**Steps to Reproduce**
Click the "ccd drop button"

**Versions**
- Software Version 1.3.0-beta
- OS macOS

**Comment by orhoj** [comment]
This has already been fixed by https://github.com/Concordium/concordium-desktop-wallet/pull/184.
