### ISSUE TITLE
Getting back to accounts overview from "detailed overview"

### ISSUE THREAD

**Issue by EmilLa1** [Concordium/concordium-desktop-wallet#191]
**Description**

If the user is in the "detailed overview" of an account then when clicking "accounts" does not go back to the 
default accounts overview. 

**Steps to Reproduce**
Go to the "accounts overview", by clicking on "Accounts", click "Change View" and afterwards click "Accounts" in the main menu.

**Expected Result**
I would personally expect that I got back to the default view. 

**Actual Result**
I still see the "detailed" overview of the prior selected account. 

**Versions**
- Software Version 1.0.3-beta
- OS macOS

**Comment by orhoj** [comment]
Please talk to @jens-concordium about this.

**Comment by jens-concordium** [comment]
This is actually intended use, the design is just bad. We are working on improving the design.
