### ISSUE TITLE
Text fields are unresponsive after ID flow is aborted

### ISSUE THREAD

**Issue by concordium-cl** [Concordium/concordium-desktop-wallet#201]
**Bug Description**
After an ID flow is aborted, you cannot enter text in any text field (e.g. new account/identity name, node address in node settings). DW needs restart. Note that this was pbserved after aborting a hanging flow with DTS. It might not occur when aborting a flow with NB.

**Steps to Reproduce**
- create identity with DTS
--> flow will hang eventually
- abort flow by clicking X
- try to enter text in any text field

**Expected Result**
Text can be entered, e.g. issuance of a new identity can be initiated. 

**Actual Result**
All text fields are unresponsive.

**Versions**
* desktop wallet 1.3.0 beta 2 for stagenet
* iPhone 11, iOS 15.1

**Comment by shjortConcordium** [comment]
Seems to happen consistently on Windows.
I think it is the prompt, which appears when "aborting flow by clicking X", which causes this. the error only seems to trigger if it has been prompted. (And it isn't really supported by electron it seems)
The user can get out of this state by alt-tabbing, and alt-tabbing back.
