### ISSUE TITLE
Wallet crashes, when date identity attributes are missing

### ISSUE THREAD

**Issue by shjortConcordium** [Concordium/concordium-desktop-wallet#210]
**Bug Description**
I have managed to create an identity without an document issue date,
which caused my wallet to crash when I select that identity in the identities page.

**Steps to Reproduce**
Create/Edit an identity without an issue date.
Select that identity in identities page.

**Expected Result**
Identity attributes are displayed.

**Actual Result**
App crashes.

**Versions**
- v1.3.1
- Ubuntu 20.04

**Comment by orhoj** [comment]
@shjortConcordium Should this be closed?

**Comment by shjortConcordium** [comment]
> @shjortConcordium Should this be closed?

Yes, I thought the linked issue being merged would, but maybe not because of #211.
