### ISSUE TITLE
Transaction view with more than 100 last transactions

### ISSUE THREAD

**Issue by soerenbf** [Concordium/concordium-desktop-wallet#24]
**Description**
Right now, you can only browse through your entire transaction history (past latest 100 transactions) by making an account report. It should be possible for a user to get an overview of your entire history of transactions in the user-friendly view of the transaction list.

In order to realize this, we probably need to re-think how the transaction list works.

**Comment by jens-concordium** [comment]
A suggestion for a solution can now be found in Figma, on the page "Advanced Account View".
