### ISSUE TITLE
We inform the user that commission rates are changeable which is incorrect

### ISSUE THREAD

**Issue by mh-concordium** [Concordium/concordium-desktop-wallet#242]
**Bug Description**
Commission rates are fixed and the text in pool settings is written as its configurable.

**Steps to Reproduce**
Try to add baker through DW.
Pool settings are presented as changeable.

**Expected Result**
Text should be adjusted with the non configurable commission rates.

**Actual Result**
<img width="427" alt="image" src="https://user-images.githubusercontent.com/98821384/160392119-ea4b42db-6cbe-4790-826f-1c8141481fcc.png">

**Versions**
- Software Version: DW V 1.4.0-alpha.0

**Comment by soerenbf** [comment]
Yes, we should handle this better. I guess as long as it's possible to change one of the values, the text is OK. Maybe a more suitable and educating description could be:

_"When you open your baker as a pool, you earn commissions of stake delegated to your pool from other accounts:"_

Is it not implicit from the slider component that you can adjust the value if it's there?

@jens-concordium, @dg-concordium?

**Comment by mh-concordium** [comment]
"Register a baker as a pool" is maybe better since we have this kind of referencing in wallet.

![image](https://user-images.githubusercontent.com/98821384/160805119-2b19cec3-4731-455e-bcf5-5a3c810f5158.png)

**Comment by mh-concordium** [comment]
OK.

**Comment by soerenbf** [comment]
@jens-concordium, @dg-concordium, are you OK with this as well, or is there another way to make it even clearer what the action does (referring to the register baker discussion here)?
