### ISSUE TITLE
Select back in multi-sig transactions results with a blank page

### ISSUE THREAD

**Issue by mh-concordium** [Concordium/concordium-desktop-wallet#245]
**Bug Description**
Select back in multi-sig transactions results with a blank page on Windows, not on Mac. 

**Steps to Reproduce**
- Setup Desktop Wallet on Win11.
- Select Multi signature transactions.
- Select Make new proposal.
- Select Update account credentials .
- Select back.

**Expected Result**
Route back to "Multi signature transactions"

**Actual Result**
Blank page.

Note that this happens for every page inside of "Multi signature transactions" that has a back button.

**Versions**
- Software Version: DW V 1.4.0-alpha.0
- OS: Win11

**Video**
https://user-images.githubusercontent.com/98821384/160787799-eefe2418-bef2-45e4-8715-2f13d5bb490c.mp4

**Comment by shjortConcordium** [comment]
Unable to reproduce it on Linux. I guess @soerenbf will have to fix it.
