### ISSUE TITLE
Mint rate value display bug in update time parameters menu

### ISSUE THREAD

**Issue by chportma** [Concordium/concordium-desktop-wallet#252]
**Bug Description**

If the daily mint rate is set to 0.00748246766, the yearly mint rate displays a long sequences of 000000000.

**Steps to Reproduce**

Enter the menu for updating time parameters. Put 0.00748246766 as daily mint rate and 3 as reward period length (epochs). See attached screenshot for result.
<img width="1512" alt="Screenshot 2022-03-31 at 13 02 52" src="https://user-images.githubusercontent.com/89910176/161721815-fe1f8d4d-445b-4ddc-91a8-3f3ef33c9095.png">

**Versions**
- Mac OS 12.3.1
- Concordium Desktop Wallet stagenet Version 1.4.0-alpha.0 (1.4.0-alpha.0)

**Comment by shjortConcordium** [comment]
Just to confirm @chportma, the issue is only visual, not the actual value, right? (I will just show "large" values in e notation instead)

**Comment by chportma** [comment]
> Just to confirm @chportma, the issue is only visual, not the actual value, right? (I will just change it show "large" values in e notation instead)

Yes, that is right. The bug is visual. The value is correct.
