### ISSUE TITLE
Reconnecting to network - bad user experience

### ISSUE THREAD

**Issue by mh-concordium** [Concordium/concordium-desktop-wallet#254]
**Bug Description**
There are several cases in which DW will just report to the UI that it is trying to reconnect if network is unstable. Even if user doesn't do anything, the pop up window will just keep appearing until the network connection is stable again.

Another case reported to support was when closing/opening the lid.
Support ticket related: https://concordium.atlassian.net/browse/SUPPORT-1225 

**Steps to Reproduce**
1. Simulate unstable network (disconnect/connect occasionally) while trying to use DW.
2. Close/open laptop lid while DW is open.

**Expected Result**
DW should not spam with the pop up window in the cases above.
Pop up informing about unstable network should pop up only if user tries to interact with DW, like send transaction.

**Actual Result**
DW often continues to pop up the error message.

**Versions**
- Software Version: V.1.4-alpha.0

**Comment by orhoj** [comment]
@mh-concordium perhaps we should talk about this issue. The reason why it pops up even though the user is not doing anything is because the application automatically retrieves information in the background.

**Comment by abizjak** [comment]
Closing because the impact for expected users is minor, and the fix is likely going to be time consuming.
