### ISSUE TITLE
UI Bug

### ISSUE THREAD

**Issue by mh-concordium** [Concordium/concordium-desktop-wallet#264]
**Bug Description**
Selecting more options broke the account view.

**Steps to Reproduce**
DW->Accounts->Account->More options

**Expected Result**
UI should stay stable.

**Actual Result**
<img width="1251" alt="image" src="https://user-images.githubusercontent.com/98821384/162399720-93f08342-0802-4806-8ac6-6d4ab617e155.png">

**Versions**
- Software Version:V 1.4.0-beta.0

**Comment by shjortConcordium** [comment]
Yeah...
Workaround: have more than one account :upside_down_face:
