### ISSUE TITLE
Pool parameters confusing after PU for a baker.

### ISSUE THREAD

**Issue by EmilLa1** [Concordium/concordium-desktop-wallet#311]
**Description**

When a baker turns into a baker automatically after the PU the initial view can seem a bit confusing. 

**Steps to Reproduce**

Become a baker before PU and after PU open the wallet and browse the overview of the baker account.

**Expected Result**

Maybe it isn't necessary to show the commissions in the default view. (They are shown anyway when you change pool parameters)

E.g. the 10% commission rate can be a bit confusing in the context that you expect that you get 100% of the rewards ('single bakerpool' and closed)

**Actual Result**

**Versions**
- Software Version 1.4.0-beta.3
- OS macOS

**Comment by EmilLa1** [comment]
<img width="435" alt="Screenshot 2022-05-23 at 12 45 23" src="https://user-images.githubusercontent.com/39825288/170039391-598518e8-73ab-4682-94fd-230235c88926.png">

**Comment by orhoj** [comment]
Suggestion: Hide commission fee fields if your baker pool is `Closed for delegation`.

**Comment by abizjak** [comment]
Jakob's suggestion sounds reasonable.
