### ISSUE TITLE
Add single signer baker flows

### ISSUE THREAD

**Issue by jens-concordium** [Concordium/concordium-desktop-wallet#33]
**Description**
At the moment baker transactions are only available via the multi-sig flows, so it would be nice to have flows for single signers. 

A suggestion for the single signer flows can be found in Figma, on the page "Single signer baker transactions". This solution is dependent on "Advanced Account View" mentioned in issue #24.

This is a nice-to-have CR, as the functionality already exists.

**Comment by soerenbf** [comment]
Agreed with @jens-concordium to deviate from the design, instead following the current convention when it comes to signing in other single-signer flows. This means having full-screen focus on the transaction being signed, along with the component showing the signing process.
