### ISSUE TITLE
Update foundation account - Blank screen

### ISSUE THREAD

**Issue by mh-concordium** [Concordium/concordium-desktop-wallet#337]
**Bug Description**
It is not possible to commit transaction because blank screen appears in DW after I selected continue.

**Steps to Reproduce**
Enable governance transactions.
Select Update foundation account.
Paste new account address and select continue.

**Expected Result**
It should be possible to commit transaction.

**Actual Result**
Blank screen.

**Versions**
- Software Version: Stagenet 1.5.0
- OS: Windows

https://user-images.githubusercontent.com/98821384/178969780-737bd977-b6d2-49ef-862b-733d71a81d0b.mp4

**Comment by orhoj** [comment]
This is a duplicate of https://github.com/Concordium/concordium-desktop-wallet/issues/328.
