### ISSUE TITLE
Import matches identities incorrectly

### ISSUE THREAD

**Issue by orhoj** [Concordium/concordium-desktop-wallet#53]
**Bug Description**
The import flow tries to match existing identities with the imported identities by using the `identityNumber` and `walletId`. However, the `walletId` may differ between the two for the same hardware wallet with identical `identifier`. Therefore the import has to use the actual identifier when matching identities.

**Steps to Reproduce**
Create identities with multiple Ledgers so that some have `walletId = 1` and some `walletId = 2`. Reset the database and perform recovery with the wallet that was previously given `walletId = 2`.

**Expected Result**
That matching identities are merged.

**Actual Result**
The recovered identity does not get the identity information from the import, but the identity is imported next to the recovered identity instead.

**Versions**
- Software Version 1.2.0-alpha

**Comment by shjortConcordium** [comment]
Can't reproduce.
