### ISSUE TITLE
Visibility of wallet version

### ISSUE THREAD

**Issue by concordium-cl** [Concordium/concordium-desktop-wallet#71]
**Description**
On small screens (e.g. laptops), the version in the left lower corner is not visible and you cannot scroll down in the task bar. A way to see it is e.g. ctrl - - on Windows. 

A use case for this is a signing ceremony where ppl must double-check the version and often bring laptops.

**Expected Result**

1. The version should be displayed under Settings > About.
2. The version should be shown on small screens as well, e.g. accessible via scrolling.

**Actual Result**
The version is not visible unless you e.g. use ctrl - - on windows.

**Versions**
- DW 1.1.6
- Windows, Lenovo ThinkPad with resolution 1920x1080

**Comment by concordium-cl** [comment]
Focus on first solution, if the other one turns out to be difficult.

**Comment by concordium-cl** [comment]
@orhoj: Could you pls assess bug, so we can talk about it Monday afternoon? Thx.

**Comment by soerenbf** [comment]
Scrolling of nav (sidebar) has already been added. I'll add an "about" link under "help" (this is convention) in the application menu bar (the native one).
