### ISSUE TITLE
Multi-signature transaction may be "signed" without confirmation on Ledger

### ISSUE THREAD

**Issue by td202** [Concordium/concordium-desktop-wallet#73]
**Bug Description**

When signing an governance update transaction, it can be that the wallet appears to produce a signature, but the ledger is not correctly used to sign the transaction.

**Steps to Reproduce**

These may not be correct/complete.

- Open the proposal to be signed
- Allow the ledger to enter the locked state
- Attempt to sign the proposal. The ledger status turns to `[Object object]`.
- Unlock the ledger and press "Sign Proposal" again.
- The transaction appears to be signed allowing export of the "signed" proposal.

**Expected Result**
After unlocking the device and choosing "Sign Proposal", the process on the device should allow signing as normal.

**Actual Result**
[update-micro-gtu-per-euro_signature-ty.json.txt](https://github.com/Concordium/concordium-desktop-wallet/files/7185024/update-micro-gtu-per-euro_signature-ty.json.txt)

**Versions**
- Software Version: 1.1.6
- Firmware Version: 0.5.0
- OS: Windows

**Comment by concordium-cl** [comment]
@orhoj: Could you pls assess bug, so we can talk about it Monday afternoon? Thx.

**Comment by orhoj** [comment]
Was this done with the Ledger on `0.5.0`? Using the released version of the Ledger application this does not happen. 

On the current development version of the Ledger there is another issue where a wrong error code is returned, which is different from this issue.

This issue could sound like multiple wallets being open at the same time, are we sure this was not the case here?

**Comment by td202** [comment]
I think I did have multiple wallets open. But Anja reportedly did not, and similarly managed to generated an invalid signature. It was version 0.5.0 (at least for me, and probably for Anja). I have not been able to reproduce it with 1.0.1.

**Comment by smh1001** [comment]
Thought to be caused by two wallets running on the same machine. We will try to see if electron supports having only one instance of the app.

**Comment by orhoj** [comment]
It seems that Electron does have some form of lock checking, but I am unsure what it actually checks for: https://stackoverflow.com/questions/35916158/how-to-prevent-multiple-instances-in-electron

**Comment by orhoj** [comment]
Electron supports one instance of an app, but we have 3: mainnet, testnet and stagenet. The fix includes using the locking and better handling of receiving responses that came from a request from a separate application.
