### ISSUE TITLE
Allow more than the minimum number of signatures on governance transactions

### ISSUE THREAD

**Issue by td202** [Concordium/concordium-desktop-wallet#74]
**Description**

It should be possible to include more than the threshold number of signatures on a governance transaction (as long as all signatures are valid). Currently the wallet does not allow adding further signatures after the threshold has been reached. The reason for this is that more than the minimum number of participants may be involved in the ceremony for redundancy, and if someone produces a valid signature, that signature should be recorded on the chain.

**Versions**
- Software Version: 1.1.6
- OS: all

**Comment by concordium-cl** [comment]
@orhoj: Could you pls assess bug, so we can talk about it Monday afternoon? Thx.

**Comment by orhoj** [comment]
This should be simple to implement, as we just hide the option to add more signatures when the threshold has been reached. We can just remove this check, which will mean that there will be no upper bound to the number of signatures (other than the one imposed by the blockchain).
